### PR TITLE
Check agent deployment based on `Ready` condition

### LINKED ISSUE #587: Status.AgentDeployed does not reflect actual agent deployment status at all times
### What steps did you take and what happened?

Management or provisioning cluster manifest reports `.status.agentDeplyment` field, which should reflect the status of the agent deployment on the child cluster. In a scenario that something or someone removes components of the agent deployment on the child cluster, the field is not getting updated, which prevents turtles from re-applying agent manifests.

### What did you expect to happen?

Turtles to be able to identify missing components on the child cluster and successfully execute import procedure.

### How to reproduce it?

It is a race condition in a scenario when the `provisioning` cluster manifest is getting replaced with `management` cluster.

It is possible to reproduce by removing some parts of the import components on the child cluster, while the agent is not connected.

Example of the failure: https://github.com/rancher/turtles/actions/runs/9709318524/attempts/1?pr=575

```yaml

apiversion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: system:serviceaccount:rancher-turtles-system:rancher-turtles-manager
  creationTimestamp: "2024-06-28T08:06:06Z"
  finalizers:
  - wrangler.cattle.io/cloud-config-secret-remover
  - wrangler.cattle.io/provisioning-cluster-remove
  - wrangler.cattle.io/rke-cluster-remove
  generation: 2
  labels:
    cluster-api.cattle.io/owned: ""
  name: clusterv1-docker-rke2-capi
  namespace: creategitops-r2rd5y
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: Cluster
    name: clusterv1-docker-rke2
    uid: 33b500f2-55ae-4759-b8f9-f8e6f57f45a9
  resourceVersion: "16050"
  uid: d1c4bd11-7c2c-4204-8710-902f87699055
spec:
  localClusterAuthEndpoint: {}
status:
  agentDeployed: true
  clusterName: c-m-vxg8zckk
  conditions:
  - lastUpdateTime: "2024-06-28T08:06:06Z"
    reason: Reconciling
    status: "True"
    type: Reconciling
  - lastUpdateTime: "2024-06-28T08:06:06Z"
    status: "False"
    type: Stalled
  - lastUpdateTime: "2024-06-28T08:08:00Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: RKECluster
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: BackingNamespaceCreated
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: DefaultProjectCreated
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: SystemProjectCreated
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: InitialRolesPopulated
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: CreatorMadeOwner
  - lastUpdateTime: "2024-06-28T08:07:40Z"
    status: "True"
    type: Pending
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    message: Waiting for API to be available
    status: Unknown
    type: Waiting
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: NoDiskPressure
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: NoMemoryPressure
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: SecretsMigrated
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: ServiceAccountSecretsMigrated
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: RKESecretsMigrated
  - lastUpdateTime: "2024-06-28T08:06:07Z"
    status: "True"
    type: ACISecretsMigrated
  - lastUpdateTime: "2024-06-28T08:08:00Z"
    status: "False"
    type: Connected
  - lastUpdateTime: "2024-06-28T08:07:40Z"
    status: "True"
    type: GlobalAdminsSynced
  - lastUpdateTime: "2024-06-28T08:07:41Z"
    status: "True"
    type: SystemAccountCreated
  - lastUpdateTime: "2024-06-28T08:07:42Z"
    status: "True"
    type: AgentDeployed
  - lastUpdateTime: "2024-06-28T08:08:00Z"
    message: Cluster agent is not connected
    reason: Disconnected
    status: "False"
    type: Ready
  fleetWorkspaceName: creategitops-r2rd5y
  observedGeneration: 2
```
Last turtles logs:
```

│ 08:22:55.134263       1 import_controller.go:131] "Reconciling CAPI cluster" controller="cluster" controllerGroup="cluster.x-k8s.io" control │
│ lerKind="Cluster" Cluster="creategitops-r2rd5y/clusterv1-docker-rke2" namespace="creategitops-r2rd5y" name="clusterv1-docker-rke2" reconcile │
│ ID="22efd157-5031-4918-a44f-5a332ccca168"                                                                                                    │
│ 08:22:55.134326       1 import_controller.go:251] "found cluster name" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKin │
│ d="Cluster" Cluster="creategitops-r2rd5y/clusterv1-docker-rke2" namespace="creategitops-r2rd5y" reconcileID="22efd157-5031-4918-a44f-5a332cc │
│ ca168" name="c-m-vxg8zckk"                                                                                                                   │
│ 08:22:55.134338       1 import_controller.go:254] "agent already deployed, no action needed" controller="cluster" controllerGroup="cluster.x │
│ -k8s.io" controllerKind="Cluster" Cluster="creategitops-r2rd5y/clusterv1-docker-rke2" namespace="creategitops-r2rd5y" name="clusterv1-docker │
│ -rke2" reconcileID="22efd157-5031-4918-a44f-5a332ccca168" 
```

Child cluster does not have a `cattle-system` namespace.
```
│ default                                                Active                                      55m                                       │
│ kube-node-lease                                        Active                                      55m                                       │
│ kube-public                                            Active                                      55m                                       │
│ kube-system                                            Active                                      55m                                       │
│ local                                                  Active                                      54m                                       │
```

### Rancher Turtles version

v0.8.0

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
**What this PR does / why we need it**:

`status.agentDeployed` and a corresponding condition in the management v3 cluster is not reflecting if the agent manifests are actually there at all times. If the old manifests are getting removed by cluster re-import or migration, new manifests can be purged by this as well. `Ready` condition should be better reflecting if turtles need to stop applying manifests.

Rancher is performing cleanup job with: https://github.com/rancher/rancher/blob/1c2b815c8dd66e141b21630904127adc8e03c3de/pkg/controllers/management/usercontrollers/controller.go#L289

We need to check for the job existence before performing import operation, and wait for the job and previous manifests to be gone if those are present.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #587 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

File: internal/controllers/import_controller.go [hunk 1]
```diff
@@ -250,7 +250,7 @@ func (r *CAPIImportReconciler) reconcileNormal(ctx context.Context, capiCluster
 
 	log.Info("found cluster name", "name", rancherCluster.Status.ClusterName)
 
-	if rancherCluster.Status.AgentDeployed {
+	if rancherCluster.Status.Ready {
 		log.Info("agent already deployed, no action needed")
```
Comment (salasberryfin) [inline internal/controllers/import_controller.go:254]:
```suggestion
		log.Info("agent is ready, no action needed")
```

File: internal/controllers/import_controller_v3.go [hunk 2]
```diff
@@ -314,7 +314,7 @@ func (r *CAPIImportManagementV3Reconciler) reconcileNormal(ctx context.Context,
 		log.Info("Successfully propagated labels to Rancher cluster")
 	}
 
-	if conditions.IsTrue(rancherCluster, managementv3.ClusterConditionAgentDeployed) {
+	if conditions.IsTrue(rancherCluster, managementv3.ClusterConditionReady) {
 		log.Info("agent already deployed, no action needed")
```
Comment (salasberryfin) [inline internal/controllers/import_controller_v3.go:318]:
```suggestion
		log.Info("agent is ready, no action needed")
```

**Review by salasberryfin — COMMENTED** [review]
Thanks @Danil-Grigorev. Just added a nit to align log message with new condition. Otherwise, LGTM.

**Review by alexander-demicev — COMMENTED** [review]
lgtm

File: internal/controllers/import_controller.go [hunk 3]
```diff
@@ -250,8 +251,8 @@ func (r *CAPIImportReconciler) reconcileNormal(ctx context.Context, capiCluster
 
 	log.Info("found cluster name", "name", rancherCluster.Status.ClusterName)
 
-	if rancherCluster.Status.AgentDeployed {
-		log.Info("agent already deployed, no action needed")
+	if conditions.IsTrue(rancherCluster, managementv3.ClusterConditionReady) {
```
Comment (alexander-demicev) [inline internal/controllers/import_controller.go:254]: does this line break V1 tests?

**Review by alexander-demicev — APPROVED** [review]

**Review by salasberryfin — APPROVED** [review]

File: internal/controllers/import_controller.go (hunk 3 above)
Comment (Danil-Grigorev) [reply internal/controllers/import_controller.go]: Seems it was not needed, so reverted it back. It should not on it’s own, but the problem was the cleanup.
