### PR TITLE
fix: remove addon finalizer

### LINKED ISSUE #2303: CAPI cluster deletion not completing after disabling CAAPF
### What steps did you take and what happened?

**Steps:**
- Install Rancher 2.13.4 & rancher-turtles-providers 0.25.4 along with fleet-addon provider
- Import Docker-RKE2 CAPI cluster into Rancher, use HelmOp for CNI
- Corresponding fleet cluster, clustergroup gets created, Rancher cluster is annotated `provisioning.cattle.io/externally-managed: 'true'`
- Upgrade Rancher to 2.14.1-alpha2 and rancher-turtles-providers to 0.26.1-rc.0
- The above step disables use-caapf feature and sets fleet-addon provider to false in providers-chart
- Delete the imported CAPI cluster
 
OR

- Install rancher-turtles-providers along with fleet-addon provider and enable use-caapf feature 
- Import Docker-RKE2 CAPI cluster into Rancher, use HelmOp for CNI
- Corresponding fleet cluster, clustergroup gets created, Rancher cluster is annotated `provisioning.cattle.io/externally-managed: 'true'`
- Disable use-caapf feature and set fleet-addon provider to false in providers-chart
- Delete the imported CAPI cluster

### What did you expect to happen?

CAPI cluster deletion happening after disabling CAAPF

### How to reproduce it?

Steps mentioned above.

### Rancher Turtles version

**Rancher**: 2.14.1-alpha2, **Turtles**: 0.26.1-rc.0

### Anything else you would like to add?
- Deletion could be stuck due to finalizer on CAPI cluster `fleet.addons.cluster.x-k8s.io`

- Fleet resources are not cleanup after disable steps
```
$ kubectl get clustergroup.fleet.cattle.io -A
NAMESPACE       NAME                               CLUSTERS-READY   BUNDLES-READY   STATUS
capi-classes    docker-rke2-example                0/0              0/0             
capi-clusters   docker-rke2-example.capi-classes   1/1              2/2             
fleet-local     default                            1/1              1/1             

$ kubectl get cluster.fleet.cattle.io -A
NAMESPACE       NAME                  BUNDLES-READY   LAST-SEEN              STATUS
capi-clusters   docker-rke2-example   2/2             2026-04-15T11:14:01Z   
fleet-local     local                 1/1             2026-04-15T11:25:48Z 
```
Found while validating https://github.com/rancher/turtles/issues/2156

### Label(s) to be applied

/kind bug

### PR DESCRIPTION
**Pull request by yiannistri**
**What this PR does / why we need it**:

This PR removes the finalizer that is added by CAAPF, when the feature gate `use-caapf` is set to false. By removing the finalizer, CAPI deletion should work as expected. The objects that CAAPF creates and are behind this finaliser (i.e. should be cleaned up) are:
- An annotation `field.cattle.io/allow-fleetworkspace-creation-for-existing-namespace` of the CAPI cluster namespace which is used to allow for existing namespaces to be created as Fleet Workspace objects.
- A BundleNamespaceMapping object which is used to map Fleet bundles to CAPI cluster namespaces ([ref](https://fleet.rancher.io/explanations/namespaces#_cross_namespace_deployments))

These 2 remaining objects will be cleaned up in a follow-up PR.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2303 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

File: internal/controllers/import_controller.go [hunk 1]
```diff
@@ -532,27 +534,43 @@ func (r *CAPIImportReconciler) optOutOfClusterOwner(ctx context.Context, rancher
...
 
 	if feature.Gates.Enabled(feature.UseCAAPF) {
-		if _, found := annotations[turtlesannotations.ExternalFleetAnnotation]; !found {
-			annotations[turtlesannotations.ExternalFleetAnnotation] = trueValue
-			rancherCluster.SetAnnotations(annotations)
+		addFleetAnnotation(ctx, annotations, rancherCluster)
 
-			log.Info("Added fleet annotation to Rancher cluster")
-		}
+		controllerutil.AddFinalizer(capiCluster, FleetAddonFinalizer)
```
Comment (anmazzotti) [inline internal/controllers/import_controller.go]: I don't think this controller should add some other controller finalizer.
CAAPF will add the finalizer back on all Clusters targeted by the FleetAddonConfig

Comment (yiannistri) [reply internal/controllers/import_controller.go]: You are right, I'll remove this part.

File: internal/controllers/import_controller.go [hunk 2]
```diff
@@ -532,27 +534,43 @@ func (r *CAPIImportReconciler) optOutOfClusterOwner(ctx context.Context, rancher
...
 	} else {
-		if _, found := annotations[turtlesannotations.ExternalFleetAnnotation]; found {
-			delete(annotations, turtlesannotations.ExternalFleetAnnotation)
-			rancherCluster.SetAnnotations(annotations)
+		removeFleetAnnotation(ctx, annotations, rancherCluster)
 
-			log.Info("Removed fleet annotation from Rancher cluster")
-		}
+		controllerutil.RemoveFinalizer(capiCluster, FleetAddonFinalizer)
```
Comment (anmazzotti) [inline internal/controllers/import_controller.go:550]: Note that CAAPF does not simply remove the finalizer. 
There is a bit of cleanup logic to delete the BundleNamespaceMapping in the ClusterClass namespace, if needed. See: https://github.com/rancher/cluster-api-addon-provider-fleet/blob/release-0.14/src/controllers/cluster.rs#L229-L289

Also FYI the cluster.fleet.cattle.io has the cluster.x-k8s.io as ownerReference and no CAAPF finalizer, so this is potentially fine.
My worry however is that, what happens if:
1. User has a Cluster provisioned with CAAPF integration
2. User updates to Turtles (using default `use-caapf:false`)
3. The CAAPF created Fleet Cluster (same namespace as CAPI Cluster) will still run. However a new Fleet Cluster will be created (in `fleet-default` namespace?). Won't the downstream cluster have 2 fleet-agents installed, or maybe 1 fleet-agent but connected to 2 Fleet Clusters on the management side? @cpinjani did you experience this?

Comment (yiannistri) [reply internal/controllers/import_controller.go:550]: @anmazzotti is it acceptable to do the cleanup for the BundleNamespaceMapping in a subsequent PR/version? I understand this is not ideal, just thinking about release timelines.

Comment (cpinjani) [reply internal/controllers/import_controller.go:550]: After user updates to `use-caapf=false` and uninstall `addonFleet` provider, there is 1 fleet-agent running on downstream cluster and below fleet resources on management cluster:

```
$ kubectl get cluster.fleet.cattle.io -A
NAMESPACE       NAME                  BUNDLES-READY   LAST-SEEN              STATUS
capi-clusters   docker-rke2-example   2/2             2026-04-17T09:54:45Z   
fleet-default   c-b4jtc               1/1             2026-04-17T10:02:17Z   
fleet-local     local                 1/1             2026-04-17T10:01:51Z   


$ kubectl get clustergroup.fleet.cattle.io -A
NAMESPACE       NAME                               CLUSTERS-READY   BUNDLES-READY   STATUS
capi-classes    docker-rke2-example                0/0              0/0             
capi-clusters   docker-rke2-example.capi-classes   1/1              2/2             
fleet-local     default                            1/1              1/1     
```

Comment (yiannistri) [reply internal/controllers/import_controller.go:550]: After discussing this with the team, it was decided to:
- Keep this PR as is, which unblocks CAPI cluster deletion.
- Create a cleanup script that replicates the CAAPF logic that deletes the BundleNamespaceMapping resource when a CAPI cluster gets deleted. The script should be part of the docs for the new release.
- Investigate why there are 2 fleet cluster definitions on the management cluster for 1 downstream cluster.

**Review by salasberryfin — APPROVED** [review]
Thanks @yiannistri

**Review by furkatgofurov7 — APPROVED** [review]
